Added plugins to monitor number of files and storages
mightyBroccoli/nextcloud-munin-py pull request #1
Opened 2018-10-31 10:49 UTC by alejandroscf

This plugins monitor the total number of files in the repository (nextcloud_files) and the number of storages available (nextcloud_storage)

2018-11-01 16:42 UTC, mightyBroccoli requested changes
Just some small things need to be changed to get this on the way to be merged.

2018-11-01 16:42 UTC, mightyBroccoli commented on nextcloud_files
> +import re
```suggestion
```
The re import is unnecessary here, as you are not using it.

2018-11-01 16:42 UTC, mightyBroccoli commented on nextcloud_files
> +                                'num_files.label number of files',
```suggestion
				'num_files.label number of files',
```
Please align your indentation to the rest of the dictionary with tab characters and not single spaces, to keep everything consistent.

2018-11-01 16:42 UTC, mightyBroccoli commented on nextcloud_files
> +		data['nextcloud_storage'].append('multigraph nextcloud_files')
```suggestion
```
This is not a multigraph plugin. Only if the plugin is outputting multiple graphs, this line is necessary.

2018-11-01 16:42 UTC, mightyBroccoli commented on nextcloud_storage
> +import re
```suggestion
```
The re import is unnecessary here, as you are not using it.

2018-11-01 16:42 UTC, mightyBroccoli commented on nextcloud_storage
> +		data['nextcloud_storage'].append('multigraph nextcloud_storage')
```suggestion
```
This is not a multigraph plugin. Only if the plugin is outputting multiple graphs, this line is necessary.

2018-11-07 15:41 UTC, mightyBroccoli requested changes
some PEP8 compliance changes needed

2018-11-07 15:41 UTC, mightyBroccoli commented on nextcloud_files
> +		data ={
```suggestion
		data = {
```
Please add a space after the operator.

2018-11-07 15:41 UTC, mightyBroccoli commented on nextcloud_files
> +	NextcloudStorage().main()
```suggestion
	NextcloudStorage().main()
	
```
PEP8 compliance: please add a newline to the end

2018-11-07 15:45 UTC, mightyBroccoli requested changes
missed one pep8 compliance issue

2018-11-07 15:45 UTC, mightyBroccoli commented on nextcloud_storage
> +		data ={
```suggestion
		data = {
```
Please add whitespaces after the operator.

2018-11-12 23:00 UTC, mightyBroccoli requested changes
PLEASE these issues are really just whitespaces please fix them

2018-11-12 23:00 UTC, mightyBroccoli commented on nextcloud_storage
> +	NextcloudStorage().main()
```suggestion
	NextcloudStorage().main()
	
```
PEP8 please finish with a new line

2018-11-13 01:27 UTC, mightyBroccoli commented
I think I'd rather have all these values ​​fetched by one plugin than two separate ones. They both fetch storage values, which would create a much clearer graph.

But I would be pleased to hear your argumentation on why you choose to use separate ones.

2018-11-13 11:47 UTC, alejandroscf commented
Sorry for the delay I was working abroad with no time to fix this errors. Thanks for the corrections.

I decided to use two graph because (at least in my case) num_files outputs a value three orders of magnitude greater than the _storage metrics (3000 vs. 3). Putting everything in the same graph made the _storage values so close to 0 that they were not useful .

2018-11-13 14:26 UTC, mightyBroccoli commented
No problem 🦄 
I threw the two plugins together yesterday evening to take a look at the resulting graph and I think you are completely right with your assumption. You can see shit with that big of an difference between the values.
![2018-11-13 15_25_20-munin munin __ magicbroccoli de __ rosewood magicbroccoli de __ nextcloud storag](https://user-images.githubusercontent.com/14238117/48419517-73c18200-e758-11e8-8f2f-9e0b8d0b89bf.png)

Just some small little changes I merge this pull request.
- the config section in the nextcloud_files script is not correctly indented
- please rename both files to xyz.py ( it seems automated testing is not working if the .py is missing )
- set the x on both files that they are executable, as munin seems to have a problem with python scripts if they are not executable

2018-11-13 15:13 UTC, alejandroscf commented
I fixed the tabs, renamed the files and made them executable.

2018-11-13 15:41 UTC, merged