Add warning to nextcloud_apps.py
mightyBroccoli/nextcloud-munin-py pull request #3
Opened 2018-11-16 15:23 UTC by alejandroscf

I've added the 'update available' warning to the non-multigraph plugin.

2018-11-16 20:16 UTC, mightyBroccoli requested changes
Mind the comma to separate dict entries.

2018-11-16 20:16 UTC, mightyBroccoli commented on nextcloud_apps.py
>  				'num_updates_available.min 0'
```suggestion
				'num_updates_available.min 0',
```

2018-11-16 20:16 UTC, mightyBroccoli commented
I have to say that I did this to my local installation too. But I was not really sure what to set the warning level/ amount to. 
Some instances with docents of apps might want a way higher warning limit.
I am quite unsure about the number.
A customisable number could grant some customisability through an env variable.

2018-11-18 19:29 UTC, alejandroscf commented
The moment you have an update available, you may have a security issue until you update that app, so I think that always rising a warning is a good move.

2018-11-19 23:31 UTC, mightyBroccoli commented
I think that your approach is better then mine. If there people start to complain with a reason the change could be done.

2018-11-19 23:32 UTC, mightyBroccoli approved these changes

2018-11-19 23:32 UTC, merged